path: C:/Users/lotus/Desktop/Mooring_Project/code/data  # dataset root dir
train: images/train
val: images/val

# Classes
names:
  0: MB   #Motor Boats
  1: MoB  #Moving Boats
  2: SB   #Sailing Boats

